New ReqLess GIS Platform/my_gis_platform/my_gis_platform/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('my_pasture.urls')),
    path("admin/", admin.site.urls),
]

New ReqLess GIS Platform/my_gis_platform/my_pasture/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dates_request, name='dates_request'),
    path('about/', views.about, name='about'),
    path('available_dates/', views.available_dates, name='available_dates'),
    path('available_dates/<int:pk>/', views.date_detail, name='date_detail'),
    path('ajax/', views.ajax_view, name='ajax'),
]

New ReqLess GIS Platform/my_gis_platform/my_pasture/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

import os
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files.storage import default_storage
from django.core.files.storage import get_storage_class


@receiver(post_save)
def clear_media_folder(sender, instance, **kwargs):
    folder_name = 'kml_files'
    file_field_name = 'kml_file'

    media_path = os.path.join(settings.MEDIA_ROOT, folder_name)

    if hasattr(instance, file_field_name) and instance.kml_file:
        try:
            storage_class = get_storage_class()
            storage = storage_class()
            storage_location = storage.location

            media_storage = FileSystemStorage(location=media_path)
            for file_name in media_storage.listdir('')[1]:
                directory, existing_file_name = os.path.split(str(getattr(instance, file_field_name)))
                if file_name != existing_file_name:
                    file_path = os.path.join(media_path, file_name)
                    os.remove(file_path)
        except Exception as e:
            print(f"Error deleting files in {media_path}: {e}")

post_save.connect(clear_media_folder)


class InputModel(models.Model):
    LEVELS = [
        ("L1C", "Level-1C"),
        ("L2A", "Level-2A"),
    ]

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    level = models.CharField(max_length=3, choices=LEVELS)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    recent_date = models.BooleanField()
    kml_file = models.FileField(upload_to='kml_files/', validators=[FileExtensionValidator(allowed_extensions=['kml'])])

New ReqLess GIS Platform/my_gis_platform/my_pasture/forms.py
from django import forms
from .models import InputModel
from django.core.exceptions import ValidationError
from datetime import date, timedelta
import re


def is_english_letters_only(filename):
    pattern = r'^[a-zA-Z.]+$'
    return re.match(pattern, filename) is not None

class DateInput(forms.DateInput):
    input_type = 'date'


class InputForm(forms.ModelForm):

    class Meta:
        model = InputModel
        fields = "__all__"
        labels = {
            "level":("Уровень спутника"),
            "start_date":("Начальная дата"),
            "end_date":("Конечная дата"),
            "recent_date":("Последняя доступная дата"),
            "kml_file":("KML файл"),
        }
        help_texts = {
            "kml_file":("KML файл с координатами пастбища"),
        }
        widgets = {
            "start_date": DateInput,
            "end_date": DateInput,
            'kml_file': forms.ClearableFileInput(attrs={'accept': '.kml, .shp'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        recent_date = cleaned_data.get('recent_date')
        kml_file = cleaned_data.get('kml_file')

        if not is_english_letters_only(kml_file.name):
            raise ValidationError("Название файла должно быть на английском")

        if not recent_date and start_date and end_date and start_date >= end_date:
            raise ValidationError('Начальная дата должна быть раньше конечной даты')

        if not recent_date and start_date and end_date and (end_date - start_date < timedelta(days=8)):
            raise ValidationError('Минимальный разрешенный интервал 9 дней')

        if (not recent_date) and (not start_date or not end_date):
            raise ValidationError('Необходимо указать диапазон дат')

New ReqLess GIS Platform/my_gis_platform/my_pasture/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from .forms import InputForm
from .models import InputModel
from django.conf import settings
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import urllib, base64
from django.http import JsonResponse
from pandas import json_normalize
from IPython.display import display

from twilio.rest import Client
from sklearn.preprocessing import StandardScaler
from keras.models import load_model
from scipy.ndimage import binary_dilation

from googletrans import Translator

import urllib.request
import urllib.error
import requests
import joblib
from bs4 import BeautifulSoup

from sentinelhub import SHConfig
from sentinelhub import SentinelHubCatalog

from datetime import timezone, timedelta
import datetime, os, csv, math, io, matplotlib, json, re, codecs, sys, random, itertools, statistics, pickle
from math import ceil
import matplotlib.pyplot as plt
import numpy as np
from shapely.ops import unary_union
from fiona.drvsupport import supported_drivers
import geopandas as gpd
from matplotlib.path import Path
from shapely.geometry import Polygon, MultiPolygon, Point, mapping

import earthpy.spatial as es
import earthpy.plot as ep
import numpy.ma as ma
from scipy.stats.mstats import gmean, hmean
import pandas as pd
import seaborn as sns
from functools import reduce

import tensorflow as tf

matplotlib.use('agg')

from sentinelhub import (
    CRS,
    BBox,
    DataCollection,
    DownloadRequest,
    MimeType,
    MosaickingOrder,
    SentinelHubDownloadClient,
    SentinelHubRequest,
    bbox_to_dimensions,
    filter_times
)
sns.set()

# The following is not a package. It is a file utils.py which should be in the same folder as this notebook.
from utils import plot_image

colors = ['tomato', 'navy', 'MediumSpringGreen', 'lightblue', 'orange', 'blue',
          'maroon', 'purple', 'yellow', 'olive', 'brown', 'cyan']


parameters_to_ignore = ["time", "sunrise", "sunset", "weathercode"]


FORECAST_PARAMETERS = [
    "temperature_2m_max",
    "temperature_2m_min",
    "apparent_temperature_max",
    "apparent_temperature_min",
    "precipitation_sum",
    "rain_sum",
    "showers_sum",
    "snowfall_sum",
    "precipitation_hours",
    "precipitation_probability_max",
    "precipitation_probability_min",
    "precipitation_probability_mean",
    "weathercode",
    "sunrise",
    "sunset",
    "windspeed_10m_max",
    "windgusts_10m_max",
    "winddirection_10m_dominant",
    "shortwave_radiation_sum",
    "et0_fao_evapotranspiration",
    "uv_index_max",
    "uv_index_clear_sky_max",]

FORECAST_RUSSIAN_PARAMETERS = [

    "температура_2м_макс",
    "температура_2м_мин",
    "температура_ощущ_макс",
    "температура_ощущ_мин",
    "осадки_сумма",
    "дождь_сумма",
    "ливни_сумма",
    "снегопад_сумма",
    "осадки_часы",
    "вероятность_осадков_макс",
    "вероятность_осадков_мин",
    "вероятность_осадков_средняя",
    "скорость_ветра_10м_макс",
    "порывы_ветра_10м_макс",
    "направление_ветра_10м",
    "коротковолновое_излучение_сумма",
    "эвапотранспирация",
    "ультрафиолетовый_индекс_макс",
    "ультрафиолетовый_индекс_чистого_неба_макс",



]
HISTORY_PARAMETERS = [
    "temperature_2m_max",
    "temperature_2m_min",
    "apparent_temperature_max",
    "apparent_temperature_min",
    "precipitation_sum",
    "rain_sum",
    "snowfall_sum",
    "precipitation_hours",
    "weathercode",
    "sunrise",
    "sunset",
    "windspeed_10m_max",
    "windgusts_10m_max",
    "winddirection_10m_dominant",
    "shortwave_radiation_sum",
    "et0_fao_evapotranspiration",]

LAST_MAIN_DISCRIPTION = ""

HISTORY_RUSSIAN_PARAMETERS = [
    "температура_2м_макс",
    "температура_2м_мин",
    "температура_ощущ_макс",
    "температура_ощущ_мин",
    "осадки_сумма",
    "дождь_сумма",
    "снегопад_сумма",
    "осадки_часы",
    "скорость_ветра_10м_макс",
    "порывы_ветра_10м_макс",
    "направление_ветра_10м",
    "коротковолновое_излучение_сумма",
    "эвапотранспирация",]



class HolderClass():
    sentinel_request = None

class EvalScripts():

    def __init__(self, bands_dict, aux_data_dict, universal_bands_dict):
        self.bands_dict = bands_dict
        self.aux_data_dict = aux_data_dict
        self.universal_bands_dict = universal_bands_dict

        self.evalscript_all_bands = """
            //VERSION=3
            function setup() {{
                return {{
                    input: [{{
                        bands: [{BANDS}],
                        units: "DN"
                    }}],
                    output: {{
                        bands: {COUNT},
                        sampleType: "INT16"
                    }}
                }};
            }}

            function evaluatePixel(sample) {{
                return [{SAMPLE}];
            }}
        """
        template1 = ""; template2 = ""
        for band in self.bands_dict.keys():
            template1 += f'"{band}", ';
            template2 += f'sample.{band}, ';
        settings = {"BANDS": template1, "SAMPLE": template2, "COUNT": str(len(self.bands_dict))}
        self.evalscript_all_bands = self.evalscript_all_bands.format(**settings)

        self.evalscript_aux_data = """
            //VERSION=3

            function setup() {{
                return {{
                    input: [{{
                        bands: [{BANDS}],
                        units: "DEGREES"
                    }}],
                    output: {{
                        bands: {COUNT},
                        sampleType: "FLOAT32"
                    }}
                }};
            }}

            function evaluatePixel(sample) {{
                return [{SAMPLE}];
            }}
        """
        template1 = ""; template2 = ""
        for band in self.aux_data_dict.keys():
            template1 += f'"{band}", ';
            template2 += f'sample.{band}, ';
        settings = {"BANDS": template1, "SAMPLE": template2, "COUNT": str(len(self.aux_data_dict))}
        self.evalscript_aux_data = self.evalscript_aux_data.format(**settings)

        if self.universal_bands_dict:
            self.universal_evalscript_all_bands = """
                //VERSION=3
                function setup() {{
                    return {{
                        input: [{{
                            bands: [{BANDS}],
                        }}],
                        output: {{
                            bands: {COUNT},
                        }}
                    }};
                }}

                function evaluatePixel(sample) {{
                    return [{SAMPLE}];
                }}
            """
            template1 = ""; template2 = ""
            for band in self.universal_bands_dict.keys():
                template1 += f'"{band}", ';
                template2 += f'sample.{band}, ';
            settings = {"BANDS": template1, "SAMPLE": template2, "COUNT": str(len(self.universal_bands_dict))}
            self.universal_evalscript_all_bands = self.universal_evalscript_all_bands.format(**settings)


def normalize(band):
    band_min, band_max = (band.min(), band.max())
    return ((band - band_min)/((band_max - band_min)))

def brighten(band):
    alpha=0.13
    beta=0
    return np.clip(alpha*band+beta, 0, 255)



class SentinelRequest():

    def __init__(self, level, start_date, end_date, recent_date, kml_file):
        self.level = level
        self.start_date = start_date
        self.end_date = end_date
        self.recent_date = recent_date
        self.kml_file = kml_file.lstrip('/')
        self.project_path = settings.BASE_DIR
        self.current_requested_index = None
        self.eng_column_names = ["temp", "feels_like", "pressure", "humidity", "dew_point", "clouds", "wind_speed", "wind_deg"]
        self.alt_eng_column_names = ["temp", "feels_like", "pressure", "humidity", "dew_point", "clouds_all", "wind_speed", "wind_deg"]
        self.rus_column_names = ["температура", "ощущается как", "атм. давление", "влажность воздуха", "точка росы", "облачность", "скорость ветра", "направление ветра"]
        self.precision = 4

        self.grand_history_weather_df = pd.read_csv('Pasture_Weather_History.csv')
        self.control_model = joblib.load('multi_target_rf_model.pkl')
        self.large_model = tf.keras.models.load_model('/large_model/')

        self.saved_mean = pd.read_pickle('saved_mean.pkl')
        self.saved_std = pd.read_pickle('saved_std.pkl')

        self.CLIENT_ID = os.getenv('CLIENT_ID')
        self.CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
        self.WEATHERAPI = os.environ.get('OpenWeatherAPIKey')

        self.config = SHConfig()

        if self.CLIENT_ID and self.CLIENT_SECRET:
            self.config.sh_client_id = self.CLIENT_ID
            self.config.sh_client_secret = self.CLIENT_SECRET

        if not self.config.sh_client_id or not self.config.sh_client_secret:
            print("Warning! To use Process API, please provide the credentials (OAuth client ID and client secret).")

        self.catalog = SentinelHubCatalog(config=self.config)

        supported_drivers['KML'] = 'rw'
        self.pasture_df = gpd.read_file(self.kml_file, driver='KML')

        self.all_zagons = []
        for zagon in range(len(self.pasture_df.index)):
            self.all_zagons.append(self.pasture_df.loc[zagon].geometry)

        self.merged_zagons = unary_union(self.all_zagons)

        x_min, y_min, x_max, y_max = self.merged_zagons.bounds
        self.pasture_coords_wgs84 = (x_min, y_min, x_max, y_max)

        self.resolution = 10
        self.pasture_bbox = BBox(bbox=self.pasture_coords_wgs84, crs=CRS.WGS84)
        self.pasture_size = bbox_to_dimensions(self.pasture_bbox, resolution=self.resolution)

        self.longitude = self.pasture_bbox.geometry.centroid.coords.xy[0][0]

New ReqLess GIS Platform/my_gis_platform/my_pasture/templates/my_pasture/about.html
{% extends "my_pasture/master.html" %}

{% block title %}
  ГИС платформа
{% endblock %}


{% block content %}


<div class="container shadow-lg mb-5"><br>

    <h1 class="text-center">ГИС платформа анализа пастбищных ресурсов</h1><br>
    <h2 class="text-center">Инструкция по применению ГИС портала</h2>
    <hr>
    <h4><span class="badge bg-success">?</span> Начальная страница:</h4>
    <hr>
    <h5>1)Выберете уровень спутника (Level-1C или Level-2A)</h5>
    <h5>2)Укажите диапазон дат для поиска или поставьте галочку в разделе "последняя доступная дата"</h5>
    <h5>3)Загрузите файл с координатами Вашего пастбища (формата .kml)</h5>
    <hr>
    <h4><span class="badge bg-success">?</span> Страница с полученными датами:</h4>
    <hr>
    <h5>1)Выберете интересующую Вас дату</h5>
    <hr>
    <h4><span class="badge bg-success">?</span> Страница анализа выбранной даты:</h4>
    <hr>
    <h5>1)Примете решение удовлетворяет ли Вас полученное изображение с точки зрения качества и наличия шумов (облаков)</h5>
    <h5>2)Пройдите в раздел заполнения формы запросов ниже</h5>
    <h5>3)Заполните ячейку формулы. Для справки обратитесь в справочник нажав кнопку "?" справа от ячейки формулы</h5>
    <h5>4)Установите пределы выводимых значении (относительная или абсолютная) *(если необходимо)</h5>
    <h5>5)Установите порог значения и его оператор *(если необходимо)</h5>
    <h5>6)Нажмите на кнопку "Прогноз"</h5>
    <h5>7)Выберете метод выбора опорного значения и введите параметры урованения кривой урожайности</h5>
    <h5>8)Получите реальные значения по загонам в тоннах на гектар</h5>
    <h5>9)Нажмите на появившуюся кнопку “Симуляция” для начала процесса симуляции стравливании на пастбище</h5>
    <h5>10)Пользователю предлагается заполнить несколько разделов включающие в себя основные параметры необходимые для инициализации растиении, КРС, технологии выпаса, пастбища и т.д. Для заполнения данных параметров от пользователя требуется владение эксперными знаниями в сфере животноводства и растениеводства, а также знание по какой технологии и в каких условиях будет проводится стравливание загонов</h5>
    <h5 class="mb-5">11)После заполнения всех соответсвующих разделов нажмита на кнопку “Начать”. Данная кнопка начнет процесс симуляции стравливания, после оканчания которой ниже на экране выведутся результаты математической симуляции в виде графов изменения урожайности загонов пастбища</h5>

</div>



{% endblock %}

New ReqLess GIS Platform/my_gis_platform/my_pasture/templates/my_pasture/available_dates.html
{% extends "my_pasture/master.html" %}

{% block title %}
  ГИС платформа
{% endblock %}

{% block content %}
<style>
    /* Custom CSS to set tooltip opacity to 1 */
    .tooltip {
      opacity: 1 !important;
    }
    .tooltip-inner {
        max-width: 100%; /* Set the maximum width to 100% */
        background-color: black; /* Set the background color to white */
        opacity: 1;
    }

    @media (min-width: 576px) {
        /* Adjust the max-width based on the window size */
        .tooltip-inner {
            max-width: 500px;
        }
    }
</style>

<div class="container mb-5">
  <div class="row">
    <div class="col-sm">
        <h4 class="text-left text-justify">Порог значения облачности</h4>
    </div>
    <div class="col-sm">
        <input class="form-control" type="number" id="filterValue" min="0" value="100">
    </div>
    <div class="col-sm">
      <button class="btn btn-primary btn-block btn-sm" type="button" onclick="iterateForms()">Фильтровать по облачности</button>
    </div>
  </div>
</div>

<div class="container"><br>

    <h1 class="text-center">ГИС платформа анализа пастбищных ресурсов</h1><br>
    <h3 class="text-center">Доступные даты на выбранный промежуток</h3>

    <div class="mb-5">
        {% if dict_of_images %}
            {% for unique_date, image in dict_of_images.items %}
                <form id="{{ unique_date.1 }}" method="POST" action="{% url 'date_detail' pk=counter_start|add:forloop.counter0 %}">
                    {% csrf_token %}
                    <input type="hidden" name="pk" id="hidden_input_tag" value="{{ counter_start|add:forloop.counter0 }}">
                    <button
                        name="date"
                        value="{{ counter_start|add:forloop.counter0 }}"
                        class="btn btn-outline-dark btn-lg btn-block ShowItsImage mt-1"
                        data-toggle="tooltip"
                        title='<img src="data:image/png;base64,{{ image }}" alt="{{ unique_date.0 }}" class="img-fluid img-thumbnail" style="opacity:1;">'
                    >
                        | {{ unique_date.0 }} | (облачность: {{ unique_date.1 }}%)
                    </button>
                </form>
            {% endfor %}
        {% endif %}
    </div>

</div>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip({
            html: true,
            trigger: 'hover',
            animation: false,
            delay: { "show": 100, "hide": 100 },
            placement: 'auto',
        });
    });

    function iterateForms() {
        var filterValue = document.getElementById("filterValue").value;
        var forms = document.forms;
        for (var i = 0; i < forms.length; i++) {
            var buttons = forms[i].getElementsByClassName('ShowItsImage');
            for (var j = 0; j < buttons.length; j++) {
                if (parseFloat(buttons[j].value) <= parseFloat(filterValue)){
                    buttons[j].removeAttribute("hidden");
                } else {
                    buttons[j].setAttribute("hidden", true);
                }
            }
        }
    }
</script>

{% endblock %}

New ReqLess GIS Platform/my_gis_platform/my_pasture/templates/my_pasture/master.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>

  {% load static %}
  <!-- {% load bootstrap4 %} {% bootstrap_css %} {% bootstrap_javascript %} -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'my_pasture/pasture.css' %}"/> -->
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css">
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@turf/turf"></script>

  <script src="https://d3js.org/d3.v6.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <!-- html2canvas -->
  <script src="https://html2canvas.hertzen.com/dist/html2canvas.js"></script>


  <style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    body {
      display: flex;
      flex-direction: column;
    }
    footer {
      margin-top: auto;
      background-color: #f5f5f5;
      padding: 20px;
    }
    #spinner {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      /* Add additional styling as per your needs */
    }

  </style>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow p-3 mb-5">
    <a class="navbar-brand" href="/">Домой</a>
    <a class="navbar-brand" href="/about">Инструкция</a>
  </nav>

  {% block content %}
  {% endblock %}


<footer class="bg-dark text-center text-white shadow-lg">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0);">
    © 2023 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">www.KazATRU.office.kz</a>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

New ReqLess GIS Platform/my_gis_platform/my_pasture/templates/my_pasture/pasture.html
{% extends "my_pasture/master.html" %}

{% block title %}
  ГИС платформа
{% endblock %}

{% block content %}


<style>
    .container {
      border: 0.5px solid #555;
      border-radius: 25px;
    }
</style>

<style>
.loading-spinner {
  display: none;
  width: 40px;
  height: 40px;
  border: 3px solid #f3f3f3;
  border-top: 3px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

<div class="loading-spinner">
</div>


<div id="main-content" class="container shadow p-3 mb-5 bg-white rounded"><br>

    <h1 class="text-center">ГИС платформа анализа пастбищных ресурсов</h1><br>

    <h2 class="text-center">Форма основных параметров поиска</h1>

    <div id="myAlert" class="alert alert-danger alert-dismissible fade show" role="alert" hidden="true">
    </div>

      {% load crispy_forms_filters %}

    <form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
        <input id="requst-button" class="btn btn-primary btn-lg btn-block" type="submit" value="Сделать запрос">
    </div>

    </form>

</div>


  <script>

  function setAlertText(text) {
    var alertElement = document.getElementById('myAlert');
    if (alertElement) {

      alertElement.innerHTML = text;

      alertElement.style.display = 'block';
      alertElement.hidden = false;
    }
  }


    function showLoadingSpinner() {
      document.querySelector('.loading-spinner').style.display = 'none';
    }

      $('#requst-button').click(function() {

        var fieldValue = $('#id_level').val();
        if (fieldValue === '') {
          setAlertText("Выберете уровень спутника");
          return;
        }

      var fileInput = document.getElementById('id_kml_file');
      if (!fileInput.files.length > 0) {
        setAlertText("Выберете kml файл");
        return;
      }

        document.querySelector('.loading-spinner').style.display = 'block';
        $('#main-content').hide();
      });

    window.addEventListener('load', showLoadingSpinner);
  </script>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
        var checkbox = document.getElementById('id_recent_date');
        var startDateInput = document.getElementById('id_start_date');
        var endDateInput = document.getElementById('id_end_date');

        // Load the stored state
        var checkboxState = localStorage.getItem('checkboxState');
        if (checkboxState === 'checked') {
            checkbox.checked = true;
            startDateInput.disabled = true;
            endDateInput.disabled = true;
        }


        checkbox.addEventListener('change', function () {
            localStorage.setItem('checkboxState', checkbox.checked ? 'checked' : 'unchecked');

            startDateInput.disabled = checkbox.checked;
            endDateInput.disabled = checkbox.checked;
        });
    });
  </script>

{% endblock %}